//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.0
//     from Assets/_Project/Settings/Input/APEXControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Generated wrapper for the APEXControls input action asset.
/// </summary>
public partial class @APEXControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }

    public @APEXControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""APEXControls"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""a1b2c3d4-e5f6-7890-abcd-ef1234567890"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""b2c3d4e5-f6a7-8901-bcde-f12345678901"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DebugAttack"",
                    ""type"": ""Button"",
                    ""id"": ""aa11bb22-cc33-dd44-ee55-ff6677889900"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""c3d4e5f6-a7b8-9012-cdef-123456789012"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d4e5f6a7-b8c9-0123-defa-234567890123"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e5f6a7b8-c9d0-1234-efab-345678901234"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f6a7b8c9-d0e1-2345-fabc-456789012345"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a7b8c9d0-e1f2-3456-abcd-567890123456"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrows"",
                    ""id"": ""b8c9d0e1-f2a3-4567-bcde-678901234567"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c9d0e1f2-a3b4-5678-cdef-789012345678"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d0e1f2a3-b4c5-6789-defa-890123456789"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e1f2a3b4-c5d6-7890-efab-901234567890"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f2a3b4c5-d6e7-8901-fabc-012345678901"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""ab12cd34-ef56-7890-abcd-ef1234abcdef"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DebugAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Combat"",
            ""id"": ""c0bbc0bb-0000-0000-0000-000000000001"",
            ""actions"": [
                { ""name"": ""Attack1"", ""type"": ""Button"", ""id"": ""c0bb0001-0000-0000-0000-000000000001"", ""expectedControlType"": ""Button"", ""processors"": """", ""interactions"": """", ""initialStateCheck"": false },
                { ""name"": ""Attack2"", ""type"": ""Button"", ""id"": ""c0bb0001-0000-0000-0000-000000000002"", ""expectedControlType"": ""Button"", ""processors"": """", ""interactions"": """", ""initialStateCheck"": false },
                { ""name"": ""Attack3"", ""type"": ""Button"", ""id"": ""c0bb0001-0000-0000-0000-000000000003"", ""expectedControlType"": ""Button"", ""processors"": """", ""interactions"": """", ""initialStateCheck"": false },
                { ""name"": ""Attack4"", ""type"": ""Button"", ""id"": ""c0bb0001-0000-0000-0000-000000000004"", ""expectedControlType"": ""Button"", ""processors"": """", ""interactions"": """", ""initialStateCheck"": false },
                { ""name"": ""ToggleAuto1"", ""type"": ""Button"", ""id"": ""c0bb0002-0000-0000-0000-000000000001"", ""expectedControlType"": ""Button"", ""processors"": """", ""interactions"": """", ""initialStateCheck"": false },
                { ""name"": ""ToggleAuto2"", ""type"": ""Button"", ""id"": ""c0bb0002-0000-0000-0000-000000000002"", ""expectedControlType"": ""Button"", ""processors"": """", ""interactions"": """", ""initialStateCheck"": false },
                { ""name"": ""ToggleAuto3"", ""type"": ""Button"", ""id"": ""c0bb0002-0000-0000-0000-000000000003"", ""expectedControlType"": ""Button"", ""processors"": """", ""interactions"": """", ""initialStateCheck"": false },
                { ""name"": ""ToggleAuto4"", ""type"": ""Button"", ""id"": ""c0bb0002-0000-0000-0000-000000000004"", ""expectedControlType"": ""Button"", ""processors"": """", ""interactions"": """", ""initialStateCheck"": false }
            ],
            ""bindings"": [
                { ""name"": """", ""id"": ""c0bbb001-0000-0000-0000-000000000001"", ""path"": ""<Keyboard>/1"", ""interactions"": """", ""processors"": """", ""groups"": """", ""action"": ""Attack1"", ""isComposite"": false, ""isPartOfComposite"": false },
                { ""name"": """", ""id"": ""c0bbb001-0000-0000-0000-000000000002"", ""path"": ""<Keyboard>/2"", ""interactions"": """", ""processors"": """", ""groups"": """", ""action"": ""Attack2"", ""isComposite"": false, ""isPartOfComposite"": false },
                { ""name"": """", ""id"": ""c0bbb001-0000-0000-0000-000000000003"", ""path"": ""<Keyboard>/3"", ""interactions"": """", ""processors"": """", ""groups"": """", ""action"": ""Attack3"", ""isComposite"": false, ""isPartOfComposite"": false },
                { ""name"": """", ""id"": ""c0bbb001-0000-0000-0000-000000000004"", ""path"": ""<Keyboard>/4"", ""interactions"": """", ""processors"": """", ""groups"": """", ""action"": ""Attack4"", ""isComposite"": false, ""isPartOfComposite"": false },

                { ""name"": ""Shift+1"", ""id"": ""c0bbb002-0000-0000-0000-00000000000a"", ""path"": ""OneModifier"", ""interactions"": """", ""processors"": """", ""groups"": """", ""action"": ""ToggleAuto1"", ""isComposite"": true, ""isPartOfComposite"": false },
                { ""name"": ""modifier"", ""id"": ""c0bbb002-0000-0000-0000-00000000000b"", ""path"": ""<Keyboard>/shift"", ""interactions"": """", ""processors"": """", ""groups"": """", ""action"": ""ToggleAuto1"", ""isComposite"": false, ""isPartOfComposite"": true },
                { ""name"": ""binding"", ""id"": ""c0bbb002-0000-0000-0000-00000000000c"", ""path"": ""<Keyboard>/1"", ""interactions"": """", ""processors"": """", ""groups"": """", ""action"": ""ToggleAuto1"", ""isComposite"": false, ""isPartOfComposite"": true },

                { ""name"": ""Shift+2"", ""id"": ""c0bbb002-0000-0000-0000-00000000001a"", ""path"": ""OneModifier"", ""interactions"": """", ""processors"": """", ""groups"": """", ""action"": ""ToggleAuto2"", ""isComposite"": true, ""isPartOfComposite"": false },
                { ""name"": ""modifier"", ""id"": ""c0bbb002-0000-0000-0000-00000000001b"", ""path"": ""<Keyboard>/shift"", ""interactions"": """", ""processors"": """", ""groups"": """", ""action"": ""ToggleAuto2"", ""isComposite"": false, ""isPartOfComposite"": true },
                { ""name"": ""binding"", ""id"": ""c0bbb002-0000-0000-0000-00000000001c"", ""path"": ""<Keyboard>/2"", ""interactions"": """", ""processors"": """", ""groups"": """", ""action"": ""ToggleAuto2"", ""isComposite"": false, ""isPartOfComposite"": true },

                { ""name"": ""Shift+3"", ""id"": ""c0bbb002-0000-0000-0000-00000000002a"", ""path"": ""OneModifier"", ""interactions"": """", ""processors"": """", ""groups"": """", ""action"": ""ToggleAuto3"", ""isComposite"": true, ""isPartOfComposite"": false },
                { ""name"": ""modifier"", ""id"": ""c0bbb002-0000-0000-0000-00000000002b"", ""path"": ""<Keyboard>/shift"", ""interactions"": """", ""processors"": """", ""groups"": """", ""action"": ""ToggleAuto3"", ""isComposite"": false, ""isPartOfComposite"": true },
                { ""name"": ""binding"", ""id"": ""c0bbb002-0000-0000-0000-00000000002c"", ""path"": ""<Keyboard>/3"", ""interactions"": """", ""processors"": """", ""groups"": """", ""action"": ""ToggleAuto3"", ""isComposite"": false, ""isPartOfComposite"": true },

                { ""name"": ""Shift+4"", ""id"": ""c0bbb002-0000-0000-0000-00000000003a"", ""path"": ""OneModifier"", ""interactions"": """", ""processors"": """", ""groups"": """", ""action"": ""ToggleAuto4"", ""isComposite"": true, ""isPartOfComposite"": false },
                { ""name"": ""modifier"", ""id"": ""c0bbb002-0000-0000-0000-00000000003b"", ""path"": ""<Keyboard>/shift"", ""interactions"": """", ""processors"": """", ""groups"": """", ""action"": ""ToggleAuto4"", ""isComposite"": false, ""isPartOfComposite"": true },
                { ""name"": ""binding"", ""id"": ""c0bbb002-0000-0000-0000-00000000003c"", ""path"": ""<Keyboard>/4"", ""interactions"": """", ""processors"": """", ""groups"": """", ""action"": ""ToggleAuto4"", ""isComposite"": false, ""isPartOfComposite"": true }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_Move = m_Gameplay.FindAction("Move", throwIfNotFound: true);
        m_Gameplay_DebugAttack = m_Gameplay.FindAction("DebugAttack", throwIfNotFound: true);
        // Combat
        m_Combat = asset.FindActionMap("Combat", throwIfNotFound: true);
        m_Combat_Attack1 = m_Combat.FindAction("Attack1", throwIfNotFound: true);
        m_Combat_Attack2 = m_Combat.FindAction("Attack2", throwIfNotFound: true);
        m_Combat_Attack3 = m_Combat.FindAction("Attack3", throwIfNotFound: true);
        m_Combat_Attack4 = m_Combat.FindAction("Attack4", throwIfNotFound: true);
        m_Combat_ToggleAuto1 = m_Combat.FindAction("ToggleAuto1", throwIfNotFound: true);
        m_Combat_ToggleAuto2 = m_Combat.FindAction("ToggleAuto2", throwIfNotFound: true);
        m_Combat_ToggleAuto3 = m_Combat.FindAction("ToggleAuto3", throwIfNotFound: true);
        m_Combat_ToggleAuto4 = m_Combat.FindAction("ToggleAuto4", throwIfNotFound: true);
    }

    ~@APEXControls()
    {
        UnityEngine.Debug.Assert(!m_Gameplay.enabled, "This will cause a leak and performance issues, APEXControls.Gameplay.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Combat.enabled, "This will cause a leak and performance issues, APEXControls.Combat.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private readonly InputAction m_Gameplay_Move;
    private readonly InputAction m_Gameplay_DebugAttack;
    private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();

    public struct GameplayActions
    {
        private @APEXControls m_Wrapper;

        public GameplayActions(@APEXControls wrapper) { m_Wrapper = wrapper; }

        public InputAction @Move => m_Wrapper.m_Gameplay_Move;
        public InputAction @DebugAttack => m_Wrapper.m_Gameplay_DebugAttack;

        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }

        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }

        public bool enabled => Get().enabled;

        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }

        public void AddCallbacks(IGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @DebugAttack.started += instance.OnDebugAttack;
            @DebugAttack.performed += instance.OnDebugAttack;
            @DebugAttack.canceled += instance.OnDebugAttack;
        }

        public void RemoveCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
            {
                @Move.started -= instance.OnMove;
                @Move.performed -= instance.OnMove;
                @Move.canceled -= instance.OnMove;
                @DebugAttack.started -= instance.OnDebugAttack;
                @DebugAttack.performed -= instance.OnDebugAttack;
                @DebugAttack.canceled -= instance.OnDebugAttack;
            }
        }

        public void SetCallbacks(IGameplayActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
            {
                @Move.started -= item.OnMove;
                @Move.performed -= item.OnMove;
                @Move.canceled -= item.OnMove;
                @DebugAttack.started -= item.OnDebugAttack;
                @DebugAttack.performed -= item.OnDebugAttack;
                @DebugAttack.canceled -= item.OnDebugAttack;
            }
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }

    public GameplayActions @Gameplay => new GameplayActions(this);

    public interface IGameplayActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnDebugAttack(InputAction.CallbackContext context);
    }

    // Combat
    private readonly InputActionMap m_Combat;
    private readonly InputAction m_Combat_Attack1;
    private readonly InputAction m_Combat_Attack2;
    private readonly InputAction m_Combat_Attack3;
    private readonly InputAction m_Combat_Attack4;
    private readonly InputAction m_Combat_ToggleAuto1;
    private readonly InputAction m_Combat_ToggleAuto2;
    private readonly InputAction m_Combat_ToggleAuto3;
    private readonly InputAction m_Combat_ToggleAuto4;
    private List<ICombatActions> m_CombatActionsCallbackInterfaces = new List<ICombatActions>();

    public struct CombatActions
    {
        private @APEXControls m_Wrapper;

        public CombatActions(@APEXControls wrapper) { m_Wrapper = wrapper; }

        public InputAction @Attack1 => m_Wrapper.m_Combat_Attack1;
        public InputAction @Attack2 => m_Wrapper.m_Combat_Attack2;
        public InputAction @Attack3 => m_Wrapper.m_Combat_Attack3;
        public InputAction @Attack4 => m_Wrapper.m_Combat_Attack4;
        public InputAction @ToggleAuto1 => m_Wrapper.m_Combat_ToggleAuto1;
        public InputAction @ToggleAuto2 => m_Wrapper.m_Combat_ToggleAuto2;
        public InputAction @ToggleAuto3 => m_Wrapper.m_Combat_ToggleAuto3;
        public InputAction @ToggleAuto4 => m_Wrapper.m_Combat_ToggleAuto4;

        public InputActionMap Get() { return m_Wrapper.m_Combat; }

        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }

        public bool enabled => Get().enabled;

        public static implicit operator InputActionMap(CombatActions set) { return set.Get(); }

        public void AddCallbacks(ICombatActions instance)
        {
            if (instance == null || m_Wrapper.m_CombatActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CombatActionsCallbackInterfaces.Add(instance);
            @Attack1.started += instance.OnAttack1;
            @Attack1.performed += instance.OnAttack1;
            @Attack1.canceled += instance.OnAttack1;
            @Attack2.started += instance.OnAttack2;
            @Attack2.performed += instance.OnAttack2;
            @Attack2.canceled += instance.OnAttack2;
            @Attack3.started += instance.OnAttack3;
            @Attack3.performed += instance.OnAttack3;
            @Attack3.canceled += instance.OnAttack3;
            @Attack4.started += instance.OnAttack4;
            @Attack4.performed += instance.OnAttack4;
            @Attack4.canceled += instance.OnAttack4;
            @ToggleAuto1.started += instance.OnToggleAuto1;
            @ToggleAuto1.performed += instance.OnToggleAuto1;
            @ToggleAuto1.canceled += instance.OnToggleAuto1;
            @ToggleAuto2.started += instance.OnToggleAuto2;
            @ToggleAuto2.performed += instance.OnToggleAuto2;
            @ToggleAuto2.canceled += instance.OnToggleAuto2;
            @ToggleAuto3.started += instance.OnToggleAuto3;
            @ToggleAuto3.performed += instance.OnToggleAuto3;
            @ToggleAuto3.canceled += instance.OnToggleAuto3;
            @ToggleAuto4.started += instance.OnToggleAuto4;
            @ToggleAuto4.performed += instance.OnToggleAuto4;
            @ToggleAuto4.canceled += instance.OnToggleAuto4;
        }

        public void RemoveCallbacks(ICombatActions instance)
        {
            if (m_Wrapper.m_CombatActionsCallbackInterfaces.Remove(instance))
            {
                @Attack1.started -= instance.OnAttack1;
                @Attack1.performed -= instance.OnAttack1;
                @Attack1.canceled -= instance.OnAttack1;
                @Attack2.started -= instance.OnAttack2;
                @Attack2.performed -= instance.OnAttack2;
                @Attack2.canceled -= instance.OnAttack2;
                @Attack3.started -= instance.OnAttack3;
                @Attack3.performed -= instance.OnAttack3;
                @Attack3.canceled -= instance.OnAttack3;
                @Attack4.started -= instance.OnAttack4;
                @Attack4.performed -= instance.OnAttack4;
                @Attack4.canceled -= instance.OnAttack4;
                @ToggleAuto1.started -= instance.OnToggleAuto1;
                @ToggleAuto1.performed -= instance.OnToggleAuto1;
                @ToggleAuto1.canceled -= instance.OnToggleAuto1;
                @ToggleAuto2.started -= instance.OnToggleAuto2;
                @ToggleAuto2.performed -= instance.OnToggleAuto2;
                @ToggleAuto2.canceled -= instance.OnToggleAuto2;
                @ToggleAuto3.started -= instance.OnToggleAuto3;
                @ToggleAuto3.performed -= instance.OnToggleAuto3;
                @ToggleAuto3.canceled -= instance.OnToggleAuto3;
                @ToggleAuto4.started -= instance.OnToggleAuto4;
                @ToggleAuto4.performed -= instance.OnToggleAuto4;
                @ToggleAuto4.canceled -= instance.OnToggleAuto4;
            }
        }

        public void SetCallbacks(ICombatActions instance)
        {
            foreach (var item in m_Wrapper.m_CombatActionsCallbackInterfaces)
            {
                @Attack1.started -= item.OnAttack1;
                @Attack1.performed -= item.OnAttack1;
                @Attack1.canceled -= item.OnAttack1;
                @Attack2.started -= item.OnAttack2;
                @Attack2.performed -= item.OnAttack2;
                @Attack2.canceled -= item.OnAttack2;
                @Attack3.started -= item.OnAttack3;
                @Attack3.performed -= item.OnAttack3;
                @Attack3.canceled -= item.OnAttack3;
                @Attack4.started -= item.OnAttack4;
                @Attack4.performed -= item.OnAttack4;
                @Attack4.canceled -= item.OnAttack4;
                @ToggleAuto1.started -= item.OnToggleAuto1;
                @ToggleAuto1.performed -= item.OnToggleAuto1;
                @ToggleAuto1.canceled -= item.OnToggleAuto1;
                @ToggleAuto2.started -= item.OnToggleAuto2;
                @ToggleAuto2.performed -= item.OnToggleAuto2;
                @ToggleAuto2.canceled -= item.OnToggleAuto2;
                @ToggleAuto3.started -= item.OnToggleAuto3;
                @ToggleAuto3.performed -= item.OnToggleAuto3;
                @ToggleAuto3.canceled -= item.OnToggleAuto3;
                @ToggleAuto4.started -= item.OnToggleAuto4;
                @ToggleAuto4.performed -= item.OnToggleAuto4;
                @ToggleAuto4.canceled -= item.OnToggleAuto4;
            }
            m_Wrapper.m_CombatActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }

    public CombatActions @Combat => new CombatActions(this);

    public interface ICombatActions
    {
        void OnAttack1(InputAction.CallbackContext context);
        void OnAttack2(InputAction.CallbackContext context);
        void OnAttack3(InputAction.CallbackContext context);
        void OnAttack4(InputAction.CallbackContext context);
        void OnToggleAuto1(InputAction.CallbackContext context);
        void OnToggleAuto2(InputAction.CallbackContext context);
        void OnToggleAuto3(InputAction.CallbackContext context);
        void OnToggleAuto4(InputAction.CallbackContext context);
    }
}
